#pragma once

#define CORE 1
#define COMPATIBILITY 0

#define OPENGL_CONTEXT_VERSION_MINOR 0
#define OPENGL_CONTEXT_VERSION_MAJOR 1
#define OPENGL_CONTEXT_PROFILE 2
#define OPENGL_CONTEXT_FORWARD 3
#define WINDOW_DEFAULT_OFFSET_X 4
#define WINDOW_DEFAULT_OFFSET_Y 5
#define WINDOW_DEFAULT_RESIZABLE 6
#define WINDOW_DEFAULT_FOCUSED 7
#define WINDOW_DEFAULT_MAXIMIZED 8
#define WINDOW_DEFAULT_VISIBLE 9
#define FRAMEBUFFER_RED_BITS 10
#define FRAMEBUFFER_GREEN_BITS 11
#define FRAMEBUFFER_BLUE_BITS 12 
#define FRAMEBUFFER_ALPHA_BITS 13
